Import location: C:/Users/taase/OneDrive/Desktop/PhD Workplace/TR PhD Work/Andrews
  Lab/Projects/GPR75 Project/260501_GPR75KO/260629_GPR75KO_Bandit/FED_Data_Bandit/Export_Files
Export location: C:/Users/taase/OneDrive/Desktop/PhD Workplace/TR PhD Work/Andrews
  Lab/Projects/GPR75 Project/260501_GPR75KO/260629_GPR75KO_Bandit/FED_Data_Bandit/Export_Files
Start time type: Use first timestamp
Start time: 2/07/2022 19:31:12
End time type: Use last timestamp
End time: 2/07/2022 21:48:57
Time bin (mins): 1.0
Find individual columns: true
Create sum masters: true
Create Classic metric sheets: false
Classic duration (mins): ''
Classic active poke fallback: Auto
Create plots: true
Plot preset: Full
Plot source: Both
Plot primary group: Genotype
Plot secondary group: Sex
Plot individual lines: false
Shade dark phases: true
Use custom plot colors: true
Use settings file: false
Settings import location: C:/Users/taase/OneDrive/Desktop/PhD Workplace/TR PhD Work/Andrews
  Lab/Projects/GPR75 Project/250924_GPR75KO/251114_GPR75KO_ClosedEcon/251114_GPR75KO_ClosedEcon_Data/Export_Files/Settings_excel_file0.xlsx
Light cycle start: '21:00:00'
Light cycle end: '9:00:00'
